project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Jens Lemb"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: default
    css: styles.css
    toc: false
    anchor-sections: false
    

editor: visual

